[package]
name = "cve_2020_0796"
version = "0.1.0"
authors = ["0xeb_bp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntapi = "0.3.3"
winapi = { version = "^0.3.6", features = ["processthreadsapi", "memoryapi", "psapi", "handleapi"] }